<?php
use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>

<ul>
    <li>ToDo 1</li>
    <li>Todo 2</li>
    <li>todo 3</li>
</ul>
<div data-bind="scope: 'todo'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "todo": {
                        "component": "MageMastery_Todo/js/view/todo",
                        "template": "MageMastery_Todo/todo"
                    }
                }
            }
        }
    }
</script>
