<?php
/** @var $block Magento\Wishlist\Block\Link
 * @var \Magento\Framework\Escaper $escaper*/
?>
<li class="item link compare" data-bind="scope: 'compareProducts'" data-role="compare-products-link">
    <a class="action compare" title="<?= $escaper->escapeHtmlAttr(__('Compare Products')) ?>"
       data-bind="attr: {'href': compareProducts().listUrl}"
    >
        <span class="zmdi zmdi-swap"></span>
       <span class="title"><?= $escaper->escapeHtml(__('Compare Products')) ?></span>
        <span class="counter qty" data-bind="text: compareProducts().countCaption ? compareProducts().countCaption : 0"></span>
    </a>
</li>
<script type="text/x-magento-init">
{"[data-role=compare-products-link]": {"Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>}}
</script>
