<?php
/**
 * @var \Magento\Customer\Block\Account\AuthorizationLink $block
 * @var \Magento\Framework\Escaper $escaper
 */
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<li class="link authorization-link" data-label="<?= $escaper->escapeHtml(__('or')) ?>">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?>
        <?= /* @noEscape */ $dataPostParam ?>>
        <span class="zmdi zmdi-account"></span>
        <span class="title"><?= $escaper->escapeHtml($block->getLabel()) ?></span>
    </a>
</li>
