<?php

/** @var \Magento\Newsletter\Block\Subscribe $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<div class="block newsletter">
    <div class="title"><strong><?= $escaper->escapeHtml(__('Newsletter')) ?></strong></div>
    <div class="content">
        <form class="form subscribe"
              novalidate
              action="<?= $escaper->escapeUrl($block->getFormActionUrl()) ?>"
              method="post"
              data-mage-init='{"validation": {"errorClass": "mage-error"}}'
              id="newsletter-validate-detail">
            <div class="field newsletter">
                <div class="control">
                    <label for="newsletter">
                        <span class="label">
                            <?= $escaper->escapeHtml(__('Sign Up for Our Newsletter:')) ?>
                        </span>
                        <input name="email" type="email" id="newsletter"
                               placeholder="<?= $escaper->escapeHtml(__('Enter your e-mail')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}"
                        />
                    </label>
                    <div class="personal-data-agreement">
                        <label class="agreement-label" for="agreement">
                            <input name="agreement" type="checkbox" id="agreement"
                                   data-validate="{required:true}"/>
                            <span class="title">
                            <?= $escaper->escapeHtml(__('I consent to the processing of personal data and agree to the ')) ?>
                                <a href="<?= $block->getUrl('privacy-policy-cookie-restriction-mode');?>"><?= $escaper->escapeHtml(__('Privacy policy')) ?></a>
                            </span>
                        </label>

                    </div>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary"
                        title="<?= $escaper->escapeHtmlAttr(__('Subscribe')) ?>"
                        type="submit"
                        aria-label="Subscribe">
                    <span><?= $escaper->escapeHtml(__('Subscribe')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "newsletter-validate-detail"
            }
        }
    }
</script>
