<?php

/**
 * @var \Magento\Customer\Block\Account\AuthorizationLink $block
 * @var \Magento\Framework\Escaper $escaper
 */
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<li class="link authorization-link" data-label="<?= $escaper->escapeHtml(__('or')) ?>">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?>
    <i class="zmdi zmdi-account"></i>
    <span class="text"><?= /* @noEscape */ $dataPostParam ?><?= $escaper->escapeHtml($block->getLabel()) ?></span>
    </a>
</li>
